const KEY_MON = 'KEY_MON';
const KEY_GIA = 'KEY_GIA';
const KEY_SO_LUONG = 'KEY_SO_LUONG';
const KEY_THANH_TIEN = 'KEY_THANH_TIEN';
const KEY_MENU_ITEM = 'KEY_MENU_ITEM';
const KEY_TABLE_ITEM = 'KEY_TABLE_ITEM';

export { KEY_MON, KEY_GIA, KEY_SO_LUONG, KEY_THANH_TIEN, KEY_MENU_ITEM, KEY_TABLE_ITEM };
